### PR TITLE
ARTEMIS-297 Handle Exceptions during server stop

### PR DESCRIPTION
**Pull request by mtaylor**
Stopping the server should be able to handle exceptions thrown by
individual components.  Before this patch the stop method would throw
any raised exception and exit.  This can lead to partial shutdowns of
the server resulting in leaking threads.  This patch catches any
component exceptions and logs an appropriate error message, allowing the
server to properly shutdown.

(cherry picked from commit 046c3b19422c821136c36bf65f65e674e071a44f)

Conflicts:
	artemis-server/src/main/java/org/apache/activemq/artemis/core/server/ActiveMQServerLogger.java

### CODE REVIEW

**Comment by andytaylor** [comment]
can you add the eap Jira to the commit message please

**Comment by clebertsuconic** [comment]
@mtaylor  can you please also include 9a2bebe443528d0e6d00ea2a9cd6509fe406b91a as part of your PR? it is related to this change. I did right after I merged it into master

**Comment by mtaylor** [comment]
@andytaylor JIRA URL added.

**Comment by mtaylor** [comment]
@clebertsuconic I've added your commit to the PR as requested.  cheers.

**Pull request merged**
