### PR TITLE
JBEAP-5662

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/JBEAP-4772 7.0.z issue (pm and qa acked, missing dev ack, not in payload yet)

cherry pick two upstream commits:
https://github.com/rh-messaging/jboss-activemq-artemis/commit/bf4796c5d30d90b46b22764d638fc074c026b4b9
https://github.com/rh-messaging/jboss-activemq-artemis/commit/858d7a1a02ec18e253a9caba54e8d3cad9f04eed

upstream 7.1.0 issue https://issues.jboss.org/browse/JBEAP-5662

### CODE REVIEW

**Comment by wolfc** [comment]
We need resolution which branch is for EAP 7.0 vs 7.1 first.

**Comment by andytaylor** [comment]
yes closing as this is a 7.1 issue

**Comment by soul2zimate** [comment]
https://issues.jboss.org/browse/JBEAP-4772 is a 7.0.x CP issue with PM and QA Acks, but there is no plan yet for CP payload.

**Comment by andytaylor** [comment]
https://issues.jboss.org/browse/JBEAP-5662  is not tho

**Comment by soul2zimate** [comment]
Yes, I put both issues in description and commit message as 7.x and 7.0.x are sharing same version 1.1.0.SP18-redhat-1.

**Comment by andytaylor** [comment]
thats not how it works, this is the product branch for 7.0.x, only issues identified in the 7.0.x upgrade Jira can be sent to this branch.

**Comment by soul2zimate** [comment]
https://issues.jboss.org/browse/JBEAP-4772 7.0.x one is marked "incorporated by" the upgrade Jira by the GSS representative.

**Comment by andytaylor** [comment]
again, https://issues.jboss.org/browse/JBEAP-5662 is not

**Comment by wolfc** [comment]
@andytaylor Chao needs to know which branch https://issues.jboss.org/browse/JBEAP-5662 is supposed to be fixed in.
Then he can split off a new PR (EAP 7.1) which serves as the upstream of this PR (EAP 7.0.z).

**Comment by andytaylor** [comment]
currently there is no 7.1 branch. A decision needs to made by the EAP/Wildfly team as to what that will be based on.

**Comment by soul2zimate** [comment]
I can not reopen this one.

upstream issue is https://issues.jboss.org/browse/JBEAP-5662
upstream fixes are in branch jboss-1.4.0-x
https://github.com/rh-messaging/jboss-activemq-artemis/commit/bf4796c5d30d90b46b22764d638fc074c026b4b9
https://github.com/rh-messaging/jboss-activemq-artemis/commit/858d7a1a02ec18e253a9caba54e8d3cad9f04eed

**Pull request closed without merging**
