### PR TITLE
[JBEAP-15133,ARTEMIS-1989] Replication catch up leaking files

### PR DESCRIPTION
**Pull request by spyrkob**
Related commit that broke this at https://github.com/hornetq/hornetq/commit/837694e70573069cf78d1911975bef95925b6f29

JIRA: https://issues.jboss.org/browse/JBEAP-15133

Upstream: https://issues.apache.org/jira/browse/ARTEMIS-1989 / https://issues.jboss.org/browse/ENTMQBR-1832
Upstream PR: https://github.com/apache/activemq-artemis/pull/2194

### CODE REVIEW

**Comment by spyrkob** [comment]
Note - I had to change a few things in the test to make it compile & run on 1.5.5-x branch

**Comment by spyrkob** [comment]
@clebertsuconic could you please review this backport?

**Comment by clebertsuconic** [comment]
This seems alright.  

You also need to bring he other change I made in compactor. On the journal files repository.

**Comment by spyrkob** [comment]
@clebertsuconic do you mean this one https://github.com/apache/activemq-artemis/pull/2270?

**Comment by mtaylor** [comment]
@clebertsuconic Hey Clebert, could you provide @spyrkob with a list of commits required for the change or just cherry-pick and open a PR for us.  Thanks

**Comment by clebertsuconic** [comment]
I think this is fine... although I am assuming @spyrkob you ran the test

**Pull request merged**
