### PR TITLE
ARTEMIS-332 - test added / better dealing with critical errors on paging

### PR DESCRIPTION
**Pull request by clebertsuconic**
(cherry picked from commit a5a993ed9d67e47e97a0a8198d75600188df2eae)

https://issues.jboss.org/browse/JBEAP-2544

### CODE REVIEW

**Comment by andytaylor** [comment]
have you got the correct EAP Jira for https://github.com/clebertsuconic/activemq-artemis/commit/946981a7d0fe1dfa293abdb005b88bcbfc27ef59

**Comment by clebertsuconic** [comment]
It is a generic fix. I don't think it was raised by QA. I would just keep at the main one.

**Comment by andytaylor** [comment]
it doesnt fix all 20 tests tho?

**Comment by andytaylor** [comment]
its ok, I get it.

**Pull request merged**
