### PR TITLE
[JBEAP-3176] Server logs message with queue deploy even when topic is…

### PR DESCRIPTION
**Pull request by treblereel**
… being deployed.
JBEAP7 : https://issues.jboss.org/browse/JBEAP-3176

### CODE REVIEW

**Comment by clebertsuconic** [comment]
That's not how we do things on jboss-eap...

We require a commit on master, and then a cherry-pick -x on jboss-1.1.0-x with a Pull request.

You first commit on master, then move it here with a cherry-pick.


Otherwise future updates of Artemis will bypass this change. the intention is to upgrade Wildfly to 1.3.0 (1.4.0, etc... ) and if you do changes on the jboss fork only you will endup losing your change in future updates.

**Comment by andytaylor** [comment]
Yes, please raise an Artemis Jira and fix upstream and then cherry pick.

**Comment by clebertsuconic** [comment]
Notice, apache won't recognize JBEAP issues.. you will need to raise an Artemis issue. (or on this case NO JIRA would probalby be ok).

we don't run the product branch on apache, only open source.

**Comment by andytaylor** [comment]
I would raise a JIRA and link the EAP Jira to it. this is part of the EAP worflow and helps the EAP team know what state fixes are.

**Pull request closed without merging**
