### PR TITLE
[JBEAP-15599] Fix Netty IndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/JBEAP-15599
Fix based on comment in https://issues.jboss.org/browse/ENTMQBR-2035 This only picks part of upstream commit in https://github.com/rh-messaging/jboss-activemq-artemis/commit/fe0ca4d84fc587b701e4b83ae8e5f2240c222842#diff-85a6d032ab70ab5d9bf49a071f9bcc1a

upstream issue https://issues.apache.org/jira/browse/ARTEMIS-1009
upstream PR: https://github.com/rh-messaging/jboss-activemq-artemis/commit/fe0ca4d84fc587b701e4b83ae8e5f2240c222842#diff-85a6d032ab70ab5d9bf49a071f9bcc1a

### CODE REVIEW

**Comment by franz1981** [comment]
@soul2zimate this fix is taking care of the encode part of the process while leaving the decode as it is: It would be safe to verify if it fix the issue without lefting other (critical) parts uncovered.
The upstream PR, instead, is more impactful but complete: said that, I suppose that this commit is taking care of the IIOBE in the context of the issue.

**Comment by soul2zimate** [comment]
I have modified performance test MeasurePagingMultiThreadTest as you did in ENTMQBR-2035, I can see the IndexOutOfBoundsException without this change in 1.5.5-x branch. After applying this change, the exception is gone.
Is there any way to verify other (critical part) ?

**Comment by franz1981** [comment]
That test should be just writing, while running the full CI (that has hopefully some page decoding test with no persistence) would help IMO

**Comment by soul2zimate** [comment]
I have pushed to add a test, basically a paging test for large message with persistence disabled which fails due to IndexOutOfBoundsException without the encoding fix.

**Pull request closed without merging**
