### PR TITLE
ARTEMIS-716 max replication = 0 should mean do not make copies at all

### PR DESCRIPTION
**Pull request by ppalaga**
Backport for EAP 7.0 of https://issues.apache.org/jira/browse/ARTEMIS-716 https://github.com/apache/activemq-artemis/pull/758

### CODE REVIEW

**Comment by ppalaga** [comment]
@clebertsuconic could you please review?

**Comment by mtaylor** [comment]
@ppalaga Do you have a corresponding downstream (JBEAP) JIRA for this?

**Comment by spyrkob** [comment]
This is for https://issues.jboss.org/browse/JBEAP-10974

**Comment by mtaylor** [comment]
@ppalaga @spyrkob I've updated the commit message and merged as part of: #195

**Comment by ppalaga** [comment]
@mtaylor thanks!

**Pull request closed without merging**
