### PR TITLE
 JBEAP-16092 ARTEMIS-2227 add Implementation-Version for artemis-protocols module

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/JBEAP-16092
Add Implementation-Version for bundle packaging MANIFEST.MF
upstream PR: https://github.com/apache/activemq-artemis/pull/2496
upstream issue: https://issues.apache.org/jira/browse/ARTEMIS-2227

### CODE REVIEW

**Comment by andytaylor** [comment]
I think this is on the wrong branch, it should go into the private ActiveMQ branch if its needed for 7.2 prod builds

**Comment by soul2zimate** [comment]
I am not aware of such private prod branch, this is the Artemis product maintenance branch for EAP.

**Comment by andytaylor** [comment]
for 7.1 it is but for 7.2 onwards we use https://github.com/rh-messaging/activemq-artemis

**Comment by soul2zimate** [comment]
Thanks, it's not visible repository to me. Could you add me to the repository or cherry pick this change ?

**Pull request closed without merging**
