### PR TITLE
[JBEAP-4854] java.util.MissingFormatArgumentException: Format specifier '%s' during backup activation

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/JBEAP-4854
Upstream issue: https://issues.apache.org/jira/browse/ARTEMIS-558
Upstream PR: https://github.com/apache/activemq-artemis/pull/569

### CODE REVIEW

**Comment by andytaylor** [comment]
Has this been identified by EAP QE for 7.0.2?

**Comment by iweiss** [comment]
No, I don't think it will make into 7.0.2.

**Comment by andytaylor** [comment]
actually I meant has it been identified for 7.0.3

**Comment by andytaylor** [comment]
the reason is it doesnt appear on https://issues.jboss.org/browse/JBEAP-5471

**Comment by iweiss** [comment]
Ah, sorry. It's there now.

**Comment by wolfc** [comment]
Hold horses, nobody has formally requested this for 7.0.z. The issues are a jumble.

**Comment by wolfc** [comment]
https://issues.jboss.org/browse/JBEAP-4854 has been removed from any component upgrade and is now standing correctly again for EAP 7 backlog.
This invalidates this PR, unless A-MQ has need of it.

**Comment by mtaylor** [comment]
@iweiss I'm closing this out as per @wolfc comments.  We can reopen at a later date if needed.

**Pull request closed without merging**
