### PR TITLE
JBEAP-6196

### PR DESCRIPTION
**Pull request by franz1981**
https://issues.jboss.org/browse/JBEAP-6196

(cherry picked from commit 2ed51bf3278520c466de2f568f090018988e81df)
(cherry picked from commit 2509eeb818078627838ee2cd5b828fc98c514dfa)
(cherry picked from commit 6b5fff40cb105053db7de043b9f6927d29ecc7b7)

### CODE REVIEW

**Comment by gaol** [comment]
@franz1981 @clebertsuconic  there are 4 commits in upstream PR: https://github.com/apache/activemq-artemis/pull/777 for issue addressed in https://issues.apache.org/jira/browse/ARTEMIS-734. Do you think we need cherry-pick them all to this branch or these 3 are sufficient for the fix?

**Comment by mtaylor** [comment]
@franz1981 Can you please response to @gaol  question re: commits.

**Comment by clebertsuconic** [comment]
nope.. the 4th commit is not related to this issue...

There is ActiveMQScheduledComponent upstream, which doesn't exist on this branch. there was some use of the scheduled component, which I fixed it while fixing this issue... so it's not needed and it doesn't apply.

**Comment by gaol** [comment]
@clebertsuconic Thank you for the clarification, so I think this PR is OK. :smile:

**Pull request merged**
