### PR TITLE
ARTEMIS-2085 - Improve validation of MDB activation config

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/JBEAP-14106
Upstream Issue: https://issues.jboss.org/browse/WFLY-11608 
Already merged in upstream master (https://github.com/apache/activemq-artemis/commit/39b177d0274886159c6006b83de52d7af6436ee4) and upstream 2.6.x ( https://github.com/apache/activemq-artemis/commit/fd96827e28c8dc4707007b038b0893816d983a19)

### CODE REVIEW

**Comment by rpelisse** [comment]
@jbertram as you've merge this into the upstream project, maybe you should take a look at it here too?

FYI, this is needed because as far as I know, EAP 7.2 still uses [2.6.3.redhat-00014](https://github.com/jbossas/jboss-eap7/blob/7.2.x/pom.xml#L269), so the fix you've merged upstream is going to be in Wildfly but not in EAP 7.2.

**Comment by jbertram** [comment]
I'm not clear on what this repo is for. Why not use the `rh-messaging/activemq-artemis` repo?

**Comment by rpelisse** [comment]
@jbertram  Well, maybe I'm wrong but I think the artefact 2.6.3.redhat-00014, was built from this repository (or rather that the PROD copy of this repository). In this case, let me double check that and I'll either ping you again if my change do need to go in there or I'll close this PR.

Thanks!

**Comment by rpelisse** [comment]
@jbertram Can you give me access to the *rh-messaging/activemq-artemis* ? All I get when I go to https://github.com/rh-messaging/activemq-artemis is a 404. Thanks!

**Pull request closed without merging**
